= Classpath mode

The goal of this part is to run a Java 8 application with JDK 9.

We'll keep compiling the application with a JDK 8, but we'll *run* it with a recent build of JDK 9.

The first step will be to launch the web ExampleApp, and call it from a browser or any other web client.
The second step will be to run our JUnit TestSuite.

== Using jdeps

*jdeps* will report usage of non standard API.

ifeval::["{os}" != "win"]
[source]
----
/usr/jdk/jdk-9/bin/jdeps --jdk-internals target deps/vertx-*.jar
----
endif::[]
ifeval::["{os}" == "win"]
[source]
----
"c:\Program Files\Java\jdk-9\bin\jdeps" --jdk-internals target deps/vertx-*.jar
----
endif::[]

*Diagnostic*

[source]
----
JDK Internal API               Suggested Replacement
----------------               ---------------------
sun.misc.BASE64Decoder         Use java.util.Base64 @since 1.8
sun.misc.BASE64Encoder         Use java.util.Base64 @since 1.8
sun.misc.Unsafe                See http://openjdk.java.net/jeps/260
sun.security.x509.X500Name     Use javax.security.auth.x500.X500Principal @since 1.4
----

* `sun.misc.BASE64Decoder`, `sun.misc.BASE64Encoder` :(  -> in our own source code
* `sun.misc.Unsafe`: maybe OK
* `sun.security.x509`, `sun.security.util`: :(  -> not great for HTTPS

== Running ExampleApp with JDK 9

Run the `{build}` script.
It compile the source code with JDK 8 (should work) and run with JDK 9 (should fail).

Our goal in this part is to make our app work with JDK 9. We will add the right options to achieve it.

ifeval::["{os}" != "win"]
[source]
----
$java -cp target:deps/*        \
      io.snowcamp.papaya.web.ExampleApp
----
endif::[]
ifeval::["{os}" == "win"]
[source]
----
%java% -cp target;deps\*       ^
       io.snowcamp.papaya.web.ExampleApp
----
endif::[]

=== Diagnostic #1

[source]
----
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
    at ...
----

When loading the XML configuration, we are using JAX-B which is not among the default root modules.

=== Solution #1

Add explicitly JAX-B on runtime

ifeval::["{os}" != "win"]
[source]
----
$java --add-modules java.xml.bind ...
----
endif::[]
ifeval::["{os}" == "win"]
[source]
----
%java% --add-modules java.xml.bind ...
----
endif::[]

=== Diagnostic #2

[source]
----
Exception in thread "main" java.lang.NoClassDefFoundError:
        Could not initialize class io.netty.util.internal.PlatformDependent0
    at ...
----

=== Solution #2

The real error is not visible :(

Hopefully, there is a flag to ask to print every module access violations : `-Dsun.reflect.debugModuleAccessChecks`.

ifeval::["{os}" != "win"]
[source]
----
$java -Dsun.reflect.debugModuleAccessChecks=true ...
----
endif::[]
ifeval::["{os}" == "win"]
[source]
----
%java% -Dsun.reflect.debugModuleAccessChecks=true ...
----
endif::[]

=== Diagnostic #3

[source]
----
java.lang.reflect.InaccessibleObjectException: Unable to make field long
        java.nio.Buffer.address accessible: module java.base does not
        "opens java.nio" to unnamed module @58a90037
    at ...
----

That's a better error message !

In the static initializer of PlatformDependent0, the exception is raised because the code tries to access a field of java.nui.Buffer which is not in an open package footnote:[https://github.com/netty/netty/blob/67d3a78123fa3faa85c1a150bd4ee69425079b3d/common/src/main/java/io/netty/util/internal/PlatformDependent0.java#L68].

=== Solution #3

Use the `add-opens` option.

ifeval::["{os}" != "win"]
[source]
----
$java --add-opens java.base/java.nio=ALL-UNNAMED ...
----
endif::[]
ifeval::["{os}" == "win"]
[source]
----
%java% --add-opens java.base/java.nio=ALL-UNNAMED ...
----
endif::[]

=== Diagnostic #4

[source]
----
java.lang.reflect.InaccessibleObjectException: Unable to make field protected java.util.Set
        sun.nio.ch.SelectorImpl.selectedKeys accessible: module java.base does not
        "opens sun.nio.ch" to unnamed module @588df31b
    at ...
----

Same problem as the previous one, with an other package.

=== Solution #4

Same solution as the previous one, with an other package.

ifeval::["{os}" != "win"]
[source]
----
$java --add-opens java.base/sun.nio.ch=ALL-UNNAMED ...
----
endif::[]
ifeval::["{os}" == "win"]
[source]
----
%java% --add-opens java.base/sun.nio.ch=ALL-UNNAMED ...
----
endif::[]

=== Diagnostic #5

[source]
----
java.lang.IllegalAccessException: class io.netty.resolver.dns.DnsServerAddresses cannot
        access class sun.net.dns.ResolverConfiguration (in module java.base) because module
        java.base does not export sun.net.dns to unnamed module @588df31b
    at ...
----

In the static initializer of io.netty.resolver.dns.DnsServerAddresses,
it tries to load the class sun.net.dns.ResolverConfiguration which is in a non-exported package footnote:[https://github.com/netty/netty/blob/67d3a78123fa3faa85c1a150bd4ee69425079b3d/resolver-dns/src/main/java/io/netty/resolver/dns/DnsServerAddresses.java#L49].

=== Solution #5

Use the `add-exports` option.

ifeval::["{os}" != "win"]
[source]
----
$java --add-exports java.base/sun.net.dns=ALL-UNNAMED ...
----
endif::[]
ifeval::["{os}" == "win"]
[source]
----
%java% --add-exports java.base/sun.net.dns=ALL-UNNAMED ...
----
endif::[]

Yeah, it works. (or maybe one more similar problem with jdk.internal.ref)
You should be able the access the service at http://localhost:8080/all.

== Testing the API with JDK 9

In the {build} script, comment out the run command

ifeval::["{os}" != "win"]
[source]
----
#$java -classpath target:deps/vertx-core.jar:...     \
#      ...
#      io.snowcamp.papaya.web.ExampleApp
----
endif::[]
ifeval::["{os}" == "win"]
[source]
----
rem %java% -classpath target;deps/vertx-core.jar;... ^
rem        ...
rem        io.snowcamp.papaya.web.ExampleApp
----
endif::[]

and uncomment the test command

ifeval::["{os}" != "win"]
[source]
----
$java -classpath target:deps/json.jar:deps/junit.jar:deps/hamcrest-core.jar \
      org.junit.runner.JUnitCore io.snowcamp.papaya.test.TestSuite
----
endif::[]
ifeval::["{os}" == "win"]
[source]
----
%java% -classpath target;deps/json-20160810.jar;deps/junit.jar;deps/hamcrest-core.jar ^
       org.junit.runner.JUnitCore io.snowcamp.papaya.test.TestSuite
----
endif::[]

=== Diagnostic

[source]
----
java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder
	at io.snowcamp.papaya.doc.Document.putBlob(Document.java:31)
	at io.snowcamp.papaya.test.DocumentTest.blob1(DocumentTest.java:20)
	at ...
----

The `sun.misc.BASE64Encoder` and `sun.misc.BASE64Decoder` classes do not exist anymore, they're in the "JDK removed internal API". jdeps provides some further information :

ifeval::["{os}" != "win"]
[source]
----
/usr/jdk/jdk-9/bin/jdeps --jdk-internals target/
----
endif::[]
ifeval::["{os}" == "win"]
[source]
----
"c:\Program Files\Java\jdk-9\bin\jdeps" --jdk-internals target/
----
endif::[]


=== Solution

In the `io.snowcamp.papaya.doc.Document` class, replace usages of `sun.misc.BASE64Decoder` by `java.util.Base64.Decoder` and `sun.misc.BASE64Encoder` by `java.util.Base64.Encoder`.

[source]
----
default void putBlob(String key, byte[] blob) {
  put(key, new String(Base64.getEncoder().encode(blob), StandardCharsets.ISO_8859_1));
}
default Optional<byte[]> getBlob(String key) {
  return get(key, String.class).map(base64 -> Base64.getDecoder().decode(base64));
}
----
